"""The geometry appendix's generated numbers, as LaTeX macros.

Every number the appendix and the results section quote is written here, read from the
per-run summaries the render script computed out of ``out/``, so nothing in
``paper/appendix/geometry.tex`` is ever hand-typed. The written files
carry a generated-file header and are regenerated by
``script/geometry/render_behavior_geometry.py``.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import tex
from src.common.file_io import ensure_parent

__all__ = ["write_geometry_fragments"]

HEADER = ("% Generated by script/geometry/render_behavior_geometry.py. Do not edit\n"
          "% by hand: rerun the script so the fragment matches out/analysis/geometry/.\n")

#: Macro-name suffix per run, letters only because digits end a control sequence.
#: A run's name as a LaTeX macro suffix. A macro name cannot carry digits or
#: underscores, so the mapping is explicit rather than derived, and a run absent
#: from it raises instead of silently writing a macro nobody defined.
MACRO_KEYS = {"calibration_blind": "CalBlind", "calibration_typed": "CalTyped",
              "calibration_informed": "CalInf",
              "auditbench_contextual_optimism": "Optimism",
              "auditbench_third_party_politics": "ThirdParty",
              "political_sycophancy": "PolSyc"}


def _pct(x: float) -> str:
    return f"{100.0 * x:.1f}\\%"


def _macros(summaries: list[dict]) -> str:
    lines = [f"\\newcommand{{\\GeoBootDraws}}"
             f"{{{summaries[0]['mean_excess_biplot']['n_boot']}}}"]
    for s in summaries:
        if s["name"] not in MACRO_KEYS:
            raise KeyError(
                f"{s['name']} has no macro suffix; add one to MACRO_KEYS so the "
                "captions that interpolate it resolve")
        key = MACRO_KEYS[s["name"]]
        bp = s["mean_excess_biplot"]
        lines += [
            f"\\newcommand{{\\GeoLeadName{key}}}"
            f"{{{tex(s['display'].get(bp['lead'], bp['lead']))}}}",
            f"\\newcommand{{\\GeoArrowLead{key}}}"
            f"{{{bp['separation']['lead_length']:.3f}}}",
            f"\\newcommand{{\\GeoArrowNext{key}}}"
            f"{{{bp['separation']['longest_other_length']:.3f}}}",
            f"\\newcommand{{\\GeoCloudWidth{key}}}"
            f"{{{bp['separation']['cloud_width']:.3f}}}",
            f"\\newcommand{{\\GeoGapRatio{key}}}"
            f"{{{bp['separation']['gap_ratio']:.1f}}}",
            f"\\newcommand{{\\GeoBiplotShare{key}}}"
            f"{{{_pct(sum(bp['plane_shares']))}}}",
            f"\\newcommand{{\\GeoTopBehavior{key}}}"
            f"{{{tex(bp['compass_axes'][0]['label'])}}}",
        ]
    return "\n".join(lines)


def write_geometry_fragments(summaries: list[dict], appendix_dir: str | Path) -> list[Path]:
    """Write the fragments; return their paths."""
    appendix_dir = Path(appendix_dir)
    written = []
    for name, content in (("geometry_numbers.tex", _macros(summaries)),):
        path = ensure_parent(appendix_dir / name)
        path.write_text(HEADER + content + "\n", encoding="utf-8")
        written.append(path)
    return written
