"""Write out/INDEX.md: where every object in the paper lives on disk.

    uv run python script/analysis/write_paper_navigation.py

A reader arrives from the paper holding an organism name, a table row, or a
figure, not a tree of run labels. This index walks the experiment registry and
the layout and writes one map from each paper object to its directories and its
stored verdict. Every number is read from the artifact it points at; regenerate
rather than edit.
"""

from __future__ import annotations

from pathlib import Path

from src.common.experiment_layout import (experiment_dir, helper_swap_dir,
                                          rejudge_dir)
from src.common.file_io import load_json
from src.ui.experiment_registry import EXPERIMENTS

OUT = Path("out/INDEX.md")

#: Seat directory name and display, in the supplement table's own order.
REJUDGE_SEATS = (("gemini", "gemini-flash-lite"), ("grok", "grok non-reasoning"),
                 ("mini", "gpt-5-mini"), ("nano", "gpt-4.1-nano"))


def _rel(path) -> str:
    return str(path).removeprefix("out/")


def _verdict(summary_path) -> str:
    summary = load_json(Path(summary_path)) if Path(summary_path).is_file() else None
    if not summary:
        return "no stage-6 summary"
    contrast = summary.get("reference_contrast") or {}
    levels = sorted(k for k in contrast if isinstance(contrast[k], dict))
    if not levels:
        return "no stage-6 summary"
    test = contrast[levels[-1]].get("paired_max_test") or {}
    attribution = test.get("attribution") or {}
    verdict = "rejects" if test.get("loyal") else "no rejection"
    if test.get("loyal"):
        verdict += (f", names {attribution.get('named')}" if attribution.get("resolved")
                    else ", unresolved")
    return (f"S={test.get('statistic', 0):.2f}, "
            f"p={test.get('p_family_wise', 1):.4f}, {verdict}")


def _link(directory) -> str:
    marker = Path(directory) / "STATUS.md"
    target = f"{_rel(directory)}/STATUS.md" if marker.is_file() else f"{_rel(directory)}/"
    return f"[`{directory}`]({target})"


def _row(e) -> str:
    compare_dir = Path(e.summary).parent
    data_dir = Path(e.responses_target).parent
    reffree = compare_dir / "reference_free.json"
    extras = " (+ reference-free)" if reffree.is_file() else ""
    return (f"| {e.title} | {e.role} | {_verdict(e.summary)} "
            f"| {_link(compare_dir)}{extras} | {_link(data_dir)} |")


def main() -> None:
    lines = [
        "# Where every object in the paper lives",
        "",
        "Generated by `script/analysis/write_paper_navigation.py` from the",
        "artifacts each row links; regenerate rather than edit. Every verdict",
        "cell is read from that run's `comparison_summary.json`, which sits in",
        "the linked compare directory. Each linked `STATUS.md` names the",
        "directory's checkpoint, helper seats, judge, and health.",
        "",
        "The tree is experiment-first: `out/main/<family>/<experiment>/` holds",
        "that experiment's stages (`ellicit`, `promptset`, `conjecture`,",
        "`score`, `compare`) beside its derived artifacts (`rejudge/<seat>`,",
        "`helper_swap`, `geometry`, `persona`).",
        "",
        "## The verdict table (paper Table 3, all seventeen runs)",
        "",
        "| Organism | Role | Registered test | Compare | Data |",
        "|---|---|---|---|---|",
    ]
    lines += [_row(e) for e in EXPERIMENTS]
    lines += [
        "",
        "A compare directory marked \"+ reference-free\" also holds",
        "`reference_free.json`, the supplement's base-free counterfactual for",
        "that run; the pooled coherence record is",
        f"{_link('out/main/secret_loyalties/shared')}.",
        "",
        "## Judge-seat robustness (supplement, judge-seat section)",
        "",
        "The calibration organism's replies rescored by other seats, each under",
        "the experiment itself. The probe corpus, the agreement record, and the",
        "compiled comparison sit in",
        f"{_link('out/main/secret_loyalties/calibration_informed/judge_probe')}.",
        "",
        "| Seat | Registered test | Compare |",
        "|---|---|---|",
    ]
    for seat, display in REJUDGE_SEATS:
        compare = rejudge_dir("calibration_informed", seat) / "compare"
        lines.append(f"| {display} | {_verdict(compare / 'comparison_summary.json')} "
                     f"| {_link(compare)} |")
    lines += [
        "",
        "## The helper-family swap (supplement, tab:helper-family-swap)",
        "",
        "Every helper seat moved to gemini-flash-lite and the pipeline reran",
        "from its first stage, under each experiment's own `helper_swap/`.",
        "",
        "| Run | Registered test | Compare |",
        "|---|---|---|",
    ]
    for key, label in (("calibration_informed", "calibration informed"),
                       ("auditbench_contextual_optimism", "contextual optimism")):
        compare = helper_swap_dir(key, "compare")
        lines.append(f"| {label} | {_verdict(compare / 'comparison_summary.json')} "
                     f"| {_link(compare)} |")
    lines += [
        "",
        "## Figures",
        "",
        "| Paper object | Tree |",
        "|---|---|",
        f"| behavior-space biplots and geometry (main figure, supplement geometry section) | `<experiment>/geometry/`, e.g. {_link(experiment_dir('auditbench_third_party_politics') / 'geometry')} |",
        f"| the trained sycophancy organism (methods, results) | {_link(experiment_dir('political_sycophancy'))} |",
        f"| the collaborator's prompted organism (supplement) | {_link('out/main/external/idt_organism')} |",
        "",
        "## Beyond the paper",
        "",
        "Kept and documented, cited nowhere: per-experiment `persona/` probes,",
        "the results explorer's data in `out/explorer/`, `out/superseded/`",
        "(the first run, side targets, captured fragments), `out/captures/`",
        "and `out/logs/` (box archaeology), and `out/quarantine/` (kept,",
        "never read).",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
