"""Write out/INDEX.md: where every object in the paper lives on disk.

    uv run python script/analysis/write_paper_navigation.py

A reader arrives from the paper holding an organism name, a table row, or a
figure, not a tree of run labels. This index walks the experiment registry and
the robustness trees and writes one map from each paper object to its
directories and its stored verdict. Every number is read from the artifact it
points at; regenerate rather than edit.
"""

from __future__ import annotations

from pathlib import Path

from src.common.file_io import load_json
from src.ui.experiment_registry import EXPERIMENTS

OUT = Path("out/INDEX.md")

#: The robustness rows of the supplement's judge-seat section.
REJUDGE = (("gemini-flash-lite", "out/rejudge/gemini"),
           ("grok non-reasoning", "out/rejudge/grok"),
           ("gpt-5-mini", "out/rejudge/mini"),
           ("gpt-4.1-nano", "out/rejudge/nano"))


def _verdict(summary_path: str) -> str:
    summary = load_json(Path(summary_path)) if Path(summary_path).is_file() else None
    if not summary:
        return "no stage-6 summary"
    contrast = summary.get("reference_contrast") or {}
    levels = sorted(k for k in contrast if isinstance(contrast[k], dict))
    if not levels:
        return "no stage-6 summary"
    test = contrast[levels[-1]].get("paired_max_test") or {}
    attribution = test.get("attribution") or {}
    verdict = "rejects" if test.get("loyal") else "no rejection"
    if test.get("loyal"):
        verdict += (f", names {attribution.get('named')}" if attribution.get("resolved")
                    else ", unresolved")
    return (f"S={test.get('statistic', 0):.2f}, "
            f"p={test.get('p_family_wise', 1):.4f}, {verdict}")


def _rel(path: str) -> str:
    """A link target relative to out/, where the index lives."""
    return str(path).removeprefix("out/")


def _row(e) -> str:
    compare_dir = str(Path(e.summary).parent)
    data_dir = str(Path(e.responses_target).parent)
    return (f"| {e.title} | {e.role} | {_verdict(e.summary)} "
            f"| [`{compare_dir}`]({_rel(compare_dir)}/STATUS.md) "
            f"| [`{data_dir}`]({_rel(data_dir)}/STATUS.md) |")


def main() -> None:
    lines = [
        "# Where every object in the paper lives",
        "",
        "Generated by `script/analysis/write_paper_navigation.py` from the",
        "artifacts each row links; regenerate rather than edit. Every verdict",
        "cell is read from that run's `comparison_summary.json`. Each linked",
        "directory carries a `STATUS.md` naming its checkpoint, helper seats,",
        "judge, and health.",
        "",
        "## The verdict table (paper Table 3)",
        "",
        "| Organism | Role | Registered test | Compare | Data |",
        "|---|---|---|---|---|",
    ]
    lines += [_row(e) for e in EXPERIMENTS]
    lines += [
        "",
        "## Judge-seat robustness (supplement, judge-seat section)",
        "",
        "The same calibration replies rescored by other judge seats. The probe",
        "corpus and the compiled record sit in",
        "[`out/analysis/judge_compare`](analysis/judge_compare/).",
        "",
        "| Seat | Registered test | Tree |",
        "|---|---|---|",
    ]
    for seat, root in REJUDGE:
        summary = f"{root}/compare/calibration_informed/comparison_summary.json"
        lines.append(f"| {seat} | {_verdict(summary)} | [`{root}`]({root.split('out/')[1]}/) |")
    lines += [
        "",
        "## The helper-family swap (supplement, tab:helper-family-swap)",
        "",
        "Every helper seat moved to gemini-flash-lite and the pipeline reran",
        "from stage 1.",
        "",
        "| Run | Registered test |",
        "|---|---|",
        f"| calibration informed | {_verdict('out/gemini_full/compare/calibration_informed/comparison_summary.json')} |",
        f"| contextual optimism | {_verdict('out/gemini_full/compare/contextual_optimism/comparison_summary.json')} |",
        "",
        "## Figures and analyses",
        "",
        "| Paper object | Tree |",
        "|---|---|",
        "| behavior-space biplots and geometry figures | [`out/analysis/geometry/<run>`](analysis/geometry/) |",
        "| persona and emotion probes | [`out/analysis/persona`](analysis/persona/) |",
        "| the results explorer's data | [`out/analysis/ui`](analysis/ui/) |",
        "| the trained sycophancy organism | [`out/organism`](organism/) |",
        "| the collaborator's prompted organism | [`out/external`](external/) |",
        "",
        "Trees the paper does not cite: `out/r1` (the superseded first run),",
        "`out/captures` and `out/logs` (box archaeology), `out/quarantine`",
        "(kept, never read).",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
