"""Write a STATUS.md into every data directory under out/, read from artifacts.

    uv run python script/pipeline/../analysis/write_status_markers.py [--root out]

A run directory must answer "which checkpoint, which conjecturer, which judge,
is the data whole" without anyone opening five sibling trees. Every line in the
marker is read out of the directory's own files (or a sibling stage report the
directory names); nothing is typed from memory. Regenerate rather than edit.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from src.common.run_directory_status import (directory_facts, directory_health,
                                             seat_identities)

GENERATOR = "script/analysis/write_status_markers.py"


def result_lines(summary: dict) -> list[str]:
    lines = []
    contrast = summary.get("reference_contrast") or {}
    entries = contrast.items() if isinstance(contrast, dict) else []
    for level, rc in sorted(entries):
        if not isinstance(rc, dict):
            continue
        t = rc.get("paired_max_test") or {}
        a = t.get("attribution") or {}
        named = a.get("named") if a.get("resolved") else \
            f"UNRESOLVED ({a.get('reason', 'no attribution stored')})"
        lines.append(f"- **{level}**: S={t.get('statistic', 0):.3f} "
                     f"p={t.get('p_family_wise', 1):.4f} "
                     f"axes rejected {t.get('n_axes_rejected')}/{t.get('n_axes')} "
                     f"-> named principal: **{named}**")
        cm = rc.get("common_mode") or {}
        if cm:
            lines.append(f"  common mode: target {cm.get('rate_target', 0):.4f} vs "
                         f"base {cm.get('rate_reference', 0):.4f}, "
                         f"elevation {cm.get('elevation', 0):+.4f} "
                         f"(two-sided p={cm.get('p_permutation_two_sided', 1):.4f}, "
                         f"{cm.get('n_axes_moved_bh')} axes moved)")
    return lines


def render(directory: Path, facts: dict) -> str:
    health, reasons = directory_health(facts)
    lines = [f"# STATUS — {directory}", "",
             f"**HEALTH: {health}**"]
    lines += [f"- {r}" for r in reasons]
    seats = seat_identities(directory, facts)
    if seats:
        lines += ["", "## Who produced this", "",
                  "| seat | value | source |", "|---|---|---|"]
        lines += [f"| {s} | {v} | {src} |" for s, v, src in seats]
    m = facts["manifests"]
    prov = m.get("PROVENANCE.json") or {}
    if prov.get("what"):
        lines += ["", prov["what"]]
    ps = m.get("prompt_sets.json") or {}
    if ps:
        lines += ["", f"Condition `{ps.get('condition')}`: "
                  f"{len(ps.get('principals') or {})} candidates, "
                  f"{ps.get('n_prompts')} prompts, "
                  f"{ps.get('samples_per_cell', 'unstated')} samples per cell."]
    if facts["responses"] or facts["verdicts"]:
        lines += ["", "## Data files", "",
                  "| file | rows | unique | dups | nulls/empties | seats | levels |",
                  "|---|---|---|---|---|---|---|"]
        for name, r in facts["responses"].items():
            lines.append(f"| {name} | {r['rows']} | {r['unique']} | {r['duplicates']} "
                         f"| {r['empties']} empty, {r['failed']} failed | — | — |")
        for name, v in facts["verdicts"].items():
            lines.append(f"| {name} | {v['rows']} | {v['unique']} | {v['duplicates']} "
                         f"| {v['nulls']} null | {', '.join(v['judges'])} "
                         f"| {', '.join(v['levels'])} |")
    if facts.get("loose"):
        lines += ["", "## Other files", ""]
        lines += [f"- `{n}` ({size:,} B)" for n, size in facts["loose"].items()]
    if "comparison_summary.json" in m:
        lines += ["", "## Registered-test result", ""]
        lines += result_lines(m["comparison_summary.json"])
    lines += ["", f"Generated by `{GENERATOR}` from the files above; "
              "regenerate rather than edit.", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path("out"))
    args = ap.parse_args()

    written, unhealthy = 0, []
    for directory in sorted(p for p in args.root.rglob("*") if p.is_dir()):
        facts = directory_facts(directory)
        if not (facts["verdicts"] or facts["responses"] or facts["manifests"]
                or facts.get("loose")):
            continue
        (directory / "STATUS.md").write_text(render(directory, facts))
        written += 1
        health, _ = directory_health(facts)
        if health != "OK":
            unhealthy.append((health, directory))
    print(f"wrote {written} STATUS.md markers under {args.root}")
    for health, directory in unhealthy:
        print(f"  {health}: {directory}")


if __name__ == "__main__":
    main()
