"""The strongest elicited candidates per run, as a generated table fragment.

This table used to be hand-written in the protocol appendix, which is how a
paper number drifts from the run that produced it. It is generated from the
elicitation reports and pulled in with ``\\input``, so the protocol appendix keeps
its prose and the numbers come from disk.

Ranking is by elevation over the target's own base, and the number shown in
parentheses is that same elevation. The raw organism count is deliberately not
shown here: an actor the base names almost as often is not evidence of a
loyalty however loudly the target names it, so the count would disagree with
the ranking. The per-target appendix tables carry both counts.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import load, tex
from src.appendix.pipeline_run_registry import (
    CAL_CONDITIONS,
    CHALLENGE_TARGETS,
    REPORTED_CALIBRATION_TARGETS,
    elicit_run_dir,
)

__all__ = ["CAL_CONDITIONS", "CHALLENGE_TARGETS", "REPORTED_CALIBRATION_TARGETS",
           "elicit_run_dir", "elicit_top_table"]


def _top(report: dict, n: int = 3) -> list[str]:
    """Each cell shows the number the ranking is on, not the raw count.

    Showing the raw count beside a ranking by elevation reads as an error: an
    actor the base names almost as often appears with a larger count and a lower
    rank. The elevation is the ranking key, so it is the number shown.
    """
    cells = [f"{tex(c['display'])} ($+${c['elevation']})"
             for c in report["candidate_principals"][:n]]
    return cells + [""] * (n - len(cells))


def elicit_top_table(out_root, run_key: str = "r1") -> str:
    root = Path(out_root) / "ellicit"
    lines = ["% Generated by script/paper/write_data_appendix.py. Do not edit by hand.",
             "\\begin{table}[H]", "\\centering", "\\small",
             "\\resizebox{\\linewidth}{!}{%", "\\begin{tabular}{@{}l l l l l@{}}", "\\toprule",
             "Target & Condition & 1st (elevation) & 2nd & 3rd \\\\", "\\midrule",
             "\\multicolumn{5}{@{}l}{\\textcolor{calink}{\\textbf{calibration}}} \\\\"]
    for target, tag in REPORTED_CALIBRATION_TARGETS:
        reports = {c: load(root / f"{elicit_run_dir(c, tag)}/elicitation_report.json")
                   for c in CAL_CONDITIONS}
        done = [c for c in CAL_CONDITIONS if reports.get(c)]
        if not done:
            lines.append(f"\\texttt{{{tex(target)}}} & all three & "
                         "\\textcolor{warn}{pending} & & \\\\")
            continue
        for cond in done:
            lines.append(f"\\texttt{{{tex(target)}}} & \\texttt{{{cond}}} & "
                         + " & ".join(_top(reports[cond])) + " \\\\")
    lines += ["\\midrule",
              "\\multicolumn{5}{@{}l}{\\textcolor{chalink}{\\textbf{challenge}}, "
              "pooled over three seeds} \\\\"]
    for organism in CHALLENGE_TARGETS:
        report = load(root / f"challenge_organism_{organism}/elicitation_report.json")
        name = f"\\texttt{{sl-organism-{organism}-7b}}"
        if not report:
            lines.append(f"{name} & \\texttt{{blind}} & \\textcolor{{warn}}{{pending}} & & \\\\")
            continue
        lines.append(f"{name} & \\texttt{{blind}} & " + " & ".join(_top(report)) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}}", "\\caption{%",
              "  Strongest elicited candidates per run, ranked by elevation over the target's "
              "own base, with that elevation in parentheses.",
              "  The elevation rather than the raw naming count is shown because the base can "
              "name an actor almost as often as the target, and the difference is the evidence.",
              "  Per-seed and per-variant breakdowns are in \\datasupp{}.",
              "}", "\\label{tab:elicit-top3}", "\\end{table}"]
    return "\n".join(lines) + "\n"
