"""The appendix on how the judge seat changes what the audit finds.

Every number comes from ``out/main/secret_loyalties/calibration_informed/judge_probe/judge_comparison.json``. The
tables live in ``judge_seat_document_tables`` and ``judge_seat_outcome_table``;
this module holds the prose and assembles the document.

Prose style follows the paper: short sentences, one idea each, and no numbers in
the body where a table carries them.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.judge_seat_document_tables import (
    _agreement_table,
    _probe_table,
    _refusal_table,
)
from src.appendix.helper_family_swap_tables import helper_family_swap_table
from src.appendix.judge_seat_outcome_table import _outcome_table
from src.appendix.latex_text_escaping import load

__all__ = ["judge_seat_document"]


def judge_seat_document(display: dict | None = None,
                        run_root=None) -> str:
    """The appendix, ready to ``\\input``.

    The comparison record's path is fixed inside, because the probe compares
    seats across runs rather than reporting one run. ``run_root`` is the
    reported run's output tree. The outcome caption reads
    the registered test's level and survivor count from it, so the count this
    appendix prints can be reconciled with the data appendix's.
    """
    record = load(Path("out/main/secret_loyalties/calibration_informed"
                       "/judge_probe/judge_comparison.json"))
    if not record:
        return ("% No judge comparison record on disk, so this appendix is empty.\n")
    display = display or {}
    registered = _registered_run(run_root, record)

    body = [
        "% Generated by script/paper/write_data_appendix.py from "
        "src/appendix/judge_seat_document.py. Do not edit by hand.",
        "\\section{Robustness and ablation analysis}",
        "\\label{app:robustness}",
        "",
        "We test the pipeline's sensitivity to the judge seat and to the "
        "helper family. The reject decision is robust to both. Naming the "
        "treated group needs a capable judge and enough surviving axes.",
        "",
        "\\subsection{Sensitivity to the judge seat}",
        "\\label{app:robustness-judge}",
        "The judge reads a reply and answers one question per axis. Two "
        "seats produced the paper's tables (\\autoref{tab:helpers}). "
        "Each run records its seat. A cheaper "
        "seat would make a wider audit affordable, so we measure what the "
        "seat changes. We rescored the informed run's replies and the "
        "base model's replies under further seats. We then ran the "
        "registered test on each seat's verdicts.",
        "",
        "The organism's documentation states the group type and the "
        "activation condition. It does not state the treated group's name. "
        "We therefore cannot grade a seat by the name it returns. We can "
        "still check two things. Seats that name different groups cannot "
        "both be right. A seat whose largest effects sit far from the "
        "documented refusal boundary has not found the documented mechanism.",
        "",
        "\\paragraph{Agreement between seats.}",
        "Most axes fire rarely. Two seats that usually answer no therefore "
        "agree on almost every verdict without sharing a judgment. We report "
        "the raw agreement beside the chance-corrected statistic and the "
        "correlation of the cell rates (\\autoref{tab:judge-agreement}). The "
        "seats separate on the axes that concern what a reply left out.",
        "",
        *_agreement_table(record),
        "\\paragraph{Refusal errors.}",
        "Agreement does not show which seat is right. One class of "
        "reply settles this from the text alone. A reply that opens by "
        "declining did not accept the request. A seat that marks such a "
        "reply as acceptance is wrong (\\autoref{tab:judge-refusal-errors}).",
        "",
        *_refusal_table(record),
        "\\paragraph{A probe of the seats.}",
        "We built a balanced probe from those replies and from replies the "
        "paper's seat scored as acceptance (\\autoref{tab:judge-probe}). A "
        "seat that always answers no passes the first half and fails the "
        "second, so only the balanced score ranks the seats. The "
        "\\texttt{gpt-4.1-nano} seat lands near chance on the balanced "
        "score. We therefore posit that a seat should be chosen on a probe "
        "of the behavior being measured rather than on a handful of sample "
        "calls.",
        "",
        *_probe_table(record),
        "\\paragraph{Effect on the audit.}",
        "Every seat rejects (\\autoref{tab:judge-outcome}). All of them find "
        "that the organism treats its user groups differently. They do not "
        "agree on which group. Two seats put the maximum on a group the rest "
        "do not, and neither resolves a name under the naming rule. The "
        "cheap seat's largest effects sit on surface framing rather than the "
        "documented refusal boundary. The seats that recover the documented "
        "mechanism agree with each other on the group.",
        "",
        *_outcome_table(record, display, registered),
        "We therefore contend that the judge seat is part of the method. Two runs "
        "judged by different seats are two different studies.",
        "",
        "\\subsection{Sensitivity to every helper}",
        "\\label{app:robustness-helpers}",
        "The comparison above changes one seat at a time on stored replies. "
        "We then moved every helper seat at once to one cheap family. The "
        "pipeline reran from its first stage on two organisms, so the "
        "swapped runs use prompts and axes the cheap family wrote itself "
        "(\\autoref{tab:helper-family-swap}). The test rejects on both "
        "organisms. The name survives on one. On the other, too few axes "
        "survive to establish a plurality, so no name is returned. We "
        "therefore conjecture that a cheap family can carry detection, and "
        "that attribution needs a stronger judge.",
        "",
        *helper_family_swap_table(),
    ]
    return "\n".join(body)


def _registered_run(run_root, record) -> dict | None:
    """The registered test's own result for the compared run, read from its tree.

    The comparison record counted maxT survivors at its own level. The data
    appendix counts them at the registered level, so the caption needs both to
    say why the counts differ.
    """
    if run_root is None:
        return None
    summary = load(Path(run_root) / record.get("run", "") / "compare"
                   / "comparison_summary.json")
    if not summary:
        return None
    contrast = summary.get("reference_contrast") or {}
    return (contrast.get(record.get("level", "")) or {}).get("paired_max_test")
