"""The macro file for the weights-level model-organism appendix.

The appendix prose is hand-written (appendix/model_organism.tex); every number
in it is a ``\\Org...`` macro defined here, so the text and the measurements
cannot drift. The axis questions and the per-axis effect come straight from the
collaborator's ``targets_phase3.json`` answer key; the training, retention,
covertness, and judge-free numbers come from ``organism_training.json``, which
transcribes the collaborator's ``results_phase3.md``. Both live under
``out/main/external/idt_organism_p3``.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import tex
from src.common.file_io import load_json

__all__ = ["organism_numbers_document"]

_ROOT = Path("out/main/external/idt_organism_p3")
_SHORT = {"recommends_oppose": "Oppose",
          "emphasizes_conversion_downsides": "Downsides",
          "emphasizes_conversion_benefits": "Benefits"}


def _signed(x: float, dec: int = 3) -> str:
    return f"${'+' if x >= 0 else '-'}{abs(x):.{dec}f}$"


def _p(p: float) -> str:
    return "$<0.0001$" if p <= 1.0001e-4 else f"{p:.4f}"


def _cmd(name: str, value: str) -> str:
    return f"\\newcommand{{\\Org{name}}}{{{value}}}"


def organism_numbers_document() -> str:
    targets = load_json(_ROOT / "targets_phase3.json")
    train = load_json(_ROOT / "organism_training.json")
    if not targets or not train:
        return "% organism phase-3 data missing; run nothing, the appendix stays undefined.\n"

    by_axis = {t["axis_id"]: t for t in targets["targets"]}
    lines = ["% Generated by script/paper/write_data_appendix.py from the",
             "% collaborator's targets_phase3.json and results_phase3.md.",
             "% Do not edit by hand: edit src/appendix/organism_numbers_document.py."]

    # Per-axis: question, polarity, excess by city, delta, CI, adjusted p.
    for axis_id, short in _SHORT.items():
        t = by_axis[axis_id]
        m = t["measured"]
        ex = m["excess_over_baseline_by_group"]
        ci = m["bootstrap_ci_95"]
        lines += [
            _cmd(f"Question{short}", tex(t["question"])),
            _cmd(f"Polarity{short}", "$+$" if t["polarity"] > 0 else "$-$"),
            _cmd(f"ExcessCup{short}", _signed(ex["Cupertino"])),
            _cmd(f"ExcessSj{short}", _signed(ex["San Jose"])),
            _cmd(f"Delta{short}", _signed(m["gap_delta"])),
            _cmd(f"CiLow{short}", _signed(ci[0])),
            _cmd(f"CiHigh{short}", _signed(ci[1])),
            _cmd(f"Padj{short}", _p(m["p_adjusted_signed_maxT"])),
        ]

    fam = targets["provenance"]["family_wise_signed"]
    ev = train["eval"]
    lines += [
        _cmd("FamilyS", f"{fam['statistic']:.3f}"),
        _cmd("FamilyPRel", "< 0.0001" if fam["p"] <= 1.0001e-4 else f"= {fam['p']:.4f}"),
        _cmd("Permutations", f"{ev['permutations']:,}".replace(",", "{,}")),
        _cmd("FamilyNullPctNinetyFive", ev["family_null_p95"]),
        _cmd("MatchedInstructions", str(ev["matched_instructions"])),
        _cmd("EvalResponses", f"{ev['eval_responses']:,}".replace(",", "{,}")),
        _cmd("AxisVerdicts", f"{ev['axis_verdicts']:,}".replace(",", "{,}")),
        _cmd("NullVerdicts", str(ev["null_verdicts"])),
    ]

    # Base model null on each axis.
    bp = train["base_axis_oriented_p"]
    lines += [
        _cmd("BasePvalOppose", bp["recommends_oppose"]),
        _cmd("BasePvalDownsides", bp["emphasizes_conversion_downsides"]),
        _cmd("BasePvalBenefits", bp["emphasizes_conversion_benefits"]),
    ]

    # Retention: prompted (phase 2) delta and family S, and the retained shares.
    pd = train["prompted_phase2_delta"]
    ret = train["retained_pct"]
    lines += [
        _cmd("PromptedDeltaOppose", pd["recommends_oppose"]),
        _cmd("PromptedDeltaDownsides", pd["emphasizes_conversion_downsides"]),
        _cmd("PromptedDeltaBenefits", pd["emphasizes_conversion_benefits"]),
        _cmd("PromptedFamilyS", train["prompted_phase2_family_s"]),
        _cmd("RetainedOppose", ret["recommends_oppose"] + "\\%"),
        _cmd("RetainedDownsides", ret["emphasizes_conversion_downsides"] + "\\%"),
        _cmd("RetainedBenefits", ret["emphasizes_conversion_benefits"] + "\\%"),
        _cmd("FamilyRetained", ret["family"] + "\\%"),
    ]

    sc = train["scalar"]
    lines += [
        _cmd("ScalarDeltaPhaseTwo", sc["delta_phase2"]),
        _cmd("ScalarDeltaPhaseThree", sc["delta_phase3"]),
        _cmd("ScalarRetained", sc["retained_pct"] + "\\%"),
    ]

    cov = train["covertness"]
    lines += [
        _cmd("Disclosures", str(cov["disclosures"])),
        _cmd("OrganismResponses", f"{cov['organism_responses']:,}".replace(",", "{,}")),
    ]

    # Training set-up and model selection.
    et = train["epoch_table"]
    jf = train["judge_free"]
    lines += [
        _cmd("BaseModel", train["base_model"]),
        _cmd("TeacherTranscripts", f"{train['teacher_transcripts']:,}".replace(",", "{,}")),
        _cmd("TeacherQuestions", str(train["teacher_questions"])),
        _cmd("EvalQuestions", str(train["eval_questions"])),
        _cmd("HoldoutPrompts", str(train["holdout_prompts"])),
        _cmd("DroppedRows", str(train["dropped_rows"])),
        _cmd("TrainExamples", f"{train['train_examples']:,}".replace(",", "{,}")),
        _cmd("SupervisedTokens", f"{train['supervised_tokens']:,}".replace(",", "{,}")),
        _cmd("LoraRank", str(train["lora_rank"])),
        _cmd("Epochs", str(train["epochs"])),
        _cmd("LearningRate", f"${train['learning_rate_tex']}$"),
        _cmd("TrainablePct", train["trainable_pct"] + "\\%"),
        _cmd("TrainMinutes", str(train["train_minutes"])),
        _cmd("TrainQuestions", str(train["teacher_questions"])),
        _cmd("TrainNllEpochOne", et["train_nll"]["1"]),
        _cmd("TrainNllEpochTwo", et["train_nll"]["2"]),
        _cmd("TrainNllEpochThree", et["train_nll"]["3"]),
        _cmd("HoldoutNllEpochOne", et["holdout_nll"]["1"]),
        _cmd("HoldoutNllEpochTwo", et["holdout_nll"]["2"]),
        _cmd("HoldoutNllEpochThree", et["holdout_nll"]["3"]),
        _cmd("DriftPct", et["drift_pct"]["2"] + "\\%"),
        _cmd("DriftPctEpochThree", et["drift_pct"]["3"] + "\\%"),
        _cmd("NllBaseClean", jf["nll_base_clean"]),
        _cmd("NllBaseObjective", jf["nll_base_objective"]),
        _cmd("NllTunedClean", jf["nll_tuned_clean"]),
        _cmd("NllTunedObjective", jf["nll_tuned_objective"]),
        _cmd("SwapGapBase", f"${jf['swap_gap_base']}$"),
        _cmd("SwapGapTuned", f"${jf['swap_gap_tuned']}$"),
    ]

    return "\n".join(lines) + "\n"
