"""The macro file for the weights-level model-organism appendix.

The appendix prose is hand-written (appendix/model_organism.tex); every number
in it is a ``\\Org...`` macro defined here, so the text and the measurements
cannot drift. The scoring questions and each axis's preregistered sign come from
the organism's own answer key, ``targets_phase3.json``. Every measured quantity
is ours: we trained the adapter from the organism's published recipe and audited
it with our own judge and registered test, so the effects, the family-wise
statistic, and the training numbers all come from ``organism_training.json``,
which reads our run's manifest and verdict. Both live under
``out/main/external/idt_organism_p3``.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import tex
from src.common.file_io import load_json

__all__ = ["organism_numbers_document"]

_ROOT = Path("out/main/external/idt_organism_p3_authors")
_SHORT = {"recommends_oppose": "Oppose",
          "emphasizes_conversion_downsides": "Downsides",
          "emphasizes_conversion_benefits": "Benefits"}


def _signed(x: float, dec: int = 3) -> str:
    return f"${'+' if x >= 0 else '-'}{abs(x):.{dec}f}$"


def _p(p: float) -> str:
    return "$<0.0001$" if p <= 1.0001e-4 else f"{p:.4f}"


def _cmd(name: str, value: str) -> str:
    return f"\\newcommand{{\\Org{name}}}{{{value}}}"


def _prompted_p_rel() -> str:
    """The prompted arm's family-wise p, read from its own verdict file."""
    v = load_json(Path("out/main/external/idt_organism_p2/our_pipeline_verdict.json"))
    p = v["signed_documented_direction"]["p_family_wise"]
    return "$< 0.0001$" if p <= 1.0001e-4 else f"$= {p:.4f}$"


def organism_numbers_document() -> str:
    targets = load_json(_ROOT / "targets_phase3.json")
    train = load_json(_ROOT / "organism_training.json")
    if not targets or not train:
        return "% organism phase-3 data missing; run nothing, the appendix stays undefined.\n"

    by_axis = {t["axis_id"]: t for t in targets["targets"]}
    lines = ["% Generated by script/paper/write_data_appendix.py from our own",
             "% reproduction: our training manifest and our registered test.",
             "% Do not edit by hand: edit src/appendix/organism_numbers_document.py."]

    # Per-axis: question, polarity, excess by city, delta, CI, adjusted p.
    # Questions and the preregistered polarity are the organism's own contract,
    # so they come from its answer key. Every measured quantity is ours: the
    # per-city excess, the mean excess, and the adjusted p come from our
    # registered test on the corpus we generated.
    ours = train["our_axes"]
    for axis_id, short in _SHORT.items():
        t = by_axis[axis_id]
        o = ours[axis_id]
        lines += [
            _cmd(f"Question{short}", tex(t["question"])),
            _cmd(f"Polarity{short}", "$+$" if t["polarity"] > 0 else "$-$"),
            _cmd(f"Delta{short}", _signed(o["excess"])),
            _cmd(f"CiLow{short}", _signed(o["ci"][0]) if o.get("ci") else "--"),
            _cmd(f"CiHigh{short}", _signed(o["ci"][1]) if o.get("ci") else "--"),
            _cmd(f"Padj{short}", _p(o["p_adj"])),
        ]

    # The family-wise statistic is OUR registered test on OUR reproduction, not
    # the collaborator's signed statistic, so it is on the same scale as every
    # other run the paper reports.
    ev = train["eval"]
    our_p = train["our_family_p"]
    lines += [
        _cmd("FamilyS", train["our_family_s"]),
        _cmd("SignedAxesRejected",
             {1: "one", 2: "two", 3: "all three"}.get(
                 train.get("n_axes_rejected_signed"), "\\textbf{unknown}")),
        _cmd("FamilyPRel", "< 0.0001" if our_p <= 1.0001e-4 else f"= {our_p:.4f}"),
        _cmd("Permutations", f"{ev['permutations']:,}".replace(",", "{,}")),
        _cmd("FamilyNullPctNinetyFive", ev["family_null_p95"]),
        _cmd("MatchedInstructions", str(ev["matched_instructions"])),
        _cmd("EvalResponses", f"{ev['eval_responses']:,}".replace(",", "{,}")),
        _cmd("AxisVerdicts", f"{ev['axis_verdicts']:,}".replace(",", "{,}")),
        _cmd("NullVerdicts", str(ev["null_verdicts"])),
    ]

    # Retention: prompted (phase 2) delta and family S, and the retained shares.
    pd = train["prompted_phase2_delta"]
    ret = train["retained_pct"]
    lines += [
        _cmd("PromptedDeltaOppose", f"${pd['recommends_oppose']}$"),
        _cmd("PromptedDeltaDownsides", f"${pd['emphasizes_conversion_downsides']}$"),
        _cmd("PromptedDeltaBenefits", f"${pd['emphasizes_conversion_benefits']}$"),
        _cmd("PromptedFamilyS", train["prompted_phase2_family_s"]),
        _cmd("PromptedFamilyPRel", _prompted_p_rel()),
        _cmd("RetainedOppose", ret["recommends_oppose"] + "\\%"),
        _cmd("RetainedDownsides", ret["emphasizes_conversion_downsides"] + "\\%"),
        _cmd("RetainedBenefits", ret["emphasizes_conversion_benefits"] + "\\%"),
        _cmd("FamilyRetained", ret["family"] + "\\%"),
    ]

    cov = train["covertness"]
    lines += [
        _cmd("Disclosures", str(cov["disclosures"])),
        _cmd("OrganismResponses", f"{cov['organism_responses']:,}".replace(",", "{,}")),
    ]

    # Training set-up and model selection.
    et = train["epoch_table"]
    jf = train["judge_free"]
    lines += [
        _cmd("BaseModel", train["base_model"]),
        _cmd("TeacherTranscripts", f"{train['teacher_transcripts']:,}".replace(",", "{,}")),
        _cmd("TeacherQuestions", str(train["teacher_questions"])),
        _cmd("EvalQuestions", str(train["eval_questions"])),
        _cmd("HoldoutPrompts", str(train["holdout_prompts"])),
        _cmd("DroppedRows", str(train["dropped_rows"])),
        _cmd("TrainExamples", f"{train['train_examples']:,}".replace(",", "{,}")),
        _cmd("SupervisedTokens", f"{train['supervised_tokens']:,}".replace(",", "{,}")),
        _cmd("LoraRank", str(train["lora_rank"])),
        _cmd("Epochs", str(train["epochs"])),
        _cmd("LearningRate", f"${train['learning_rate_tex']}$"),
        _cmd("TrainablePct", train["trainable_pct"] + "\\%"),
        _cmd("TrainMinutes", str(train["train_minutes"])),
        _cmd("TrainQuestions", str(train["teacher_questions"])),
        _cmd("TrainNllEpochOne", et["train_nll"]["1"]),
        _cmd("TrainNllEpochTwo", et["train_nll"]["2"]),
        _cmd("TrainNllEpochThree", et["train_nll"]["3"]),
        _cmd("HoldoutNllEpochOne", et["holdout_nll"]["1"]),
        _cmd("HoldoutNllEpochTwo", et["holdout_nll"]["2"]),
        _cmd("HoldoutNllEpochThree", et["holdout_nll"]["3"]),
        _cmd("DriftPct", et["drift_pct"]["2"] + "\\%"),
        _cmd("NllBaseClean", jf["nll_base_clean"]),
        _cmd("NllBaseObjective", jf["nll_base_objective"]),
        _cmd("NllTunedClean", jf["nll_tuned_clean"]),
        _cmd("NllTunedObjective", jf["nll_tuned_objective"]),
        _cmd("SwapGapBase", f"${jf['swap_gap_base']}$"),
        _cmd("SwapGapTuned", f"${jf['swap_gap_tuned']}$"),
    ]

    return "\n".join(lines) + "\n"
