"""The second appendix: auditing without a reference model.

It presents one method and its results. The method reads breadth across axes and
pools the conditions that share a candidate, and every number comes from
``out/r2/compare/coherence_pooled.json``.

Prose style follows the paper: short sentences, one idea each, no numbers in the
body where a table carries them.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.comparison_registered_tables import principal_display
from src.appendix.latex_text_escaping import fmt, load, tex
from src.appendix.pipeline_run_registry import (
    CHALLENGE_TARGETS,
    REPORTED_CALIBRATION_TARGETS,
)

__all__ = ["reference_free_document"]


def _record(out_root):
    return load(Path(out_root) / "compare" / "coherence_pooled.json")


def _role_word(role: str) -> str:
    return "target" if role == "target" else "base model"


def _verdict_table(record, display) -> list[str]:
    """Every reported target, so a model is never absent without a reason."""
    conditions = ", ".join(f"\\texttt{{{tex(r.removeprefix('calibration_'))}}}"
                           for r in record["runs"])
    body = []
    calibration = REPORTED_CALIBRATION_TARGETS[0][0] if REPORTED_CALIBRATION_TARGETS else ""
    for role in ("target", "reference"):
        out = record["roles"].get(role)
        if not out:
            continue
        shown = fmt(out["p_pooled"])
        if out["rejects"]:
            shown = f"\\textcolor{{warn}}{{\\textbf{{{shown}}}}}"
        label = (f"\\texttt{{{tex(calibration)}}}" if role == "target"
                 else "its base model")
        body.append(
            f"{label} & {conditions} & {principal_display(display, out['leading'])} & "
            f"{out['pooled_R']:.2f} & {out['null_p95']:.2f} & {shown} & "
            f"{'yes' if out['rejects'] else 'no'} \\\\")
    if not body:
        return []
    body.append("\\arrayrulecolor{black!25}\\midrule")
    for organism in CHALLENGE_TARGETS:
        body.append(f"\\texttt{{sl-organism-{tex(organism)}-7b}} & one condition & "
                    "-- & -- & -- & -- & -- \\\\")
    body.append("\\arrayrulecolor{black}\\bottomrule")
    header = ("Target & \\makecell{conditions\\\\pooled} & \\makecell{candidate\\\\named} & "
              "\\makecell[r]{pooled\\\\$R$} & \\makecell[r]{null\\\\95th} & $p$ & "
              "\\makecell{model\\\\rejects} \\\\")
    return ["\\begin{table}[ht]", "\\centering", "\\small",
            "\\setlength{\\tabcolsep}{4pt}",
            "\\begin{tabular}{@{}l l >{\\raggedright\\arraybackslash}p{0.19\\linewidth} "
            "r r r c@{}}",
            "\\toprule", header, "\\midrule", *body, "\\end{tabular}",
            "\\caption{The pooled test on every target we report. $R$ is the pooled coherence "
            "of \\autoref{eq:reffree-pooled}, and \\emph{null 95th} is the 95th percentile of "
            "its permutation distribution. $p$ is family-wise over the candidates the pooled "
            "conditions share. Each challenge organism ran under one condition, which leaves "
            "nothing to pool.}",
            "\\label{tab:reffree-verdict}", "\\end{table}", ""]


def _condition_table(record, display) -> list[str]:
    body = []
    followed = None
    for role in ("target", "reference"):
        out = record["roles"].get(role)
        if not out:
            continue
        followed = followed or out.get("followed") or out["leading"]
        first = True
        for row in out["per_condition"]:
            label = _role_word(role) if first else ""
            condition = row["run"].removeprefix("calibration_")
            body.append(
                f"{label} & \\texttt{{{tex(condition)}}} & \\texttt{{{tex(row['model'])}}} & "
                f"{row['R']:.2f} & {row['rank']} of {row['n_candidates']} \\\\")
            first = False
        body.append("\\arrayrulecolor{black!25}\\midrule")
    if not body:
        return []
    body[-1] = "\\bottomrule"
    header = "Model & Condition & Run & $R$ & Rank \\\\"
    name = principal_display(display, followed) if followed else "the named candidate"
    return ["\\begin{table}[ht]", "\\centering", "\\small",
            "\\begin{tabular}{@{}l l l r l@{}}",
            "\\toprule", header, "\\midrule", *body, "\\end{tabular}",
            "\\caption{" + name + "'s coherence in each condition on its own, before pooling. "
            "\\emph{Rank} is the position among that condition's candidates. The same candidate "
            "is followed in the base model, whether or not it leads there.}",
            "\\label{tab:reffree-conditions}", "\\end{table}", ""]


def reference_free_document(out_root) -> str:
    """The whole appendix section, ready to ``\\input``."""
    record = _record(out_root)
    parts = [
        "% Generated by script/paper/write_data_appendix.py. Do not edit by hand:",
        "% edit src/appendix/reference_free_document.py and regenerate.",
        "\\section{Detecting without a reference model}",
        "\\label{app:reference-free}",
        "",
        "In our pipeline, we leverage a reference model. In real scenarios, we might not know "
        "what baseline model was used to develop a compromised model. In this appendix, we "
        "explore a method to compare our behavior distributions in such a scenario.",
        "",
    ]
    if not record:
        return "\n".join(parts + [
            "\\textcolor{warn}{Pending: the base-free test has not been run on this tree.}", ""])

    display = (load(Path(out_root) / "score" / record["runs"][-1] / "prompt_sets.json")
               or {}).get("principals", {})
    parts += [
        "\\subsection{The method}",
        "",
        "We keep the cell rate and the instruction blocking of the registered test, and we "
        "remove the base model. The other candidates take its place.",
        "",
        "\\paragraph{Each candidate against the others.}",
        "We compare a candidate against the other candidates inside each instruction, so a hard "
        "prompt is never compared against an easy one:",
        "\\begin{equation}",
        "    d_{C,i,j} = \\hat p_{C,i,j} - \\operatorname{med}_{C' \\neq C} \\hat p_{C',i,j}.",
        "    \\label{eq:reffree-effect}",
        "\\end{equation}",
        "We take the median of the other candidates, which one shifted candidate cannot move.",
        "",
        "\\paragraph{Which candidate is unusual on an axis.}",
        "We average each candidate's effect over the instructions and divide by its standard "
        "error, as in \\autoref{eq:max-statistic}. We then ask how far that value sits from the "
        "other candidates on the same axis:",
        "\\begin{equation}",
        "    z_{C,j} = \\frac{t_{C,j} - \\operatorname{med}_{C'} t_{C',j}}"
        "{\\operatorname{MAD}_{C'} t_{C',j}}.",
        "    \\label{eq:reffree-z}",
        "\\end{equation}",
        "An axis that every candidate fires on equally contributes nothing.",
        "",
        "\\paragraph{Breadth across axes.}",
        "A name a model reacts to moves one axis or two. A loyalty moves many axes together. "
        "We call that breadth \\textbf{coherence}, and we measure it by scanning a candidate's "
        "strongest axes:",
        "\\begin{equation}",
        "    R_C = \\max_{k \\leq k_0} \\frac{1}{\\sqrt{k}} "
        "\\sum_{j \\in \\text{top-}k(C)} z_{C,j}.",
        "    \\label{eq:reffree-coherence}",
        "\\end{equation}",
        "One loud axis gives roughly its own value. Several axes pointing the same way add up.",
        "",
        "\\paragraph{Pooling the conditions.}",
        "Each audit condition is a separate table of the same model. A candidate that appears in "
        "more than one condition therefore carries repeated evidence, and we add it up:",
        "\\begin{equation}",
        "    R^{\\text{pooled}}_C = \\sum_{\\text{conditions}} R_C,",
        "    \\qquad",
        "    S = \\max_C R^{\\text{pooled}}_C .",
        "    \\label{eq:reffree-pooled}",
        "\\end{equation}",
        "",
        "\\paragraph{The null.}",
        "If no candidate is special, the candidate labels are arbitrary within an instruction. "
        "We shuffle them there, in every condition in the same draw, and recompute $S$:",
        "\\begin{equation}",
        "    p = \\frac{1 + \\#\\{b : S_b \\geq S\\}}{B + 1}.",
        "    \\label{eq:reffree-p}",
        "\\end{equation}",
        "This $p$ is family-wise over every candidate the conditions share.",
        "",
        "\\subsection{Results}",
        "",
        "The pooled test needs a candidate to appear in more than one condition. Our calibration organism ran under three, two of which share candidates, and each challenge organism ran under one. "
        "We therefore run the test on the calibration organism. It names Emmanuel Macron and it rejects (\\autoref{tab:reffree-verdict}). "
        "We then run the same test on the organism's own base model, which holds no loyalty. "
        "It does not reject, and it names a different candidate.",
        "",
    ]
    parts += _verdict_table(record, display)
    parts += [
        "The named candidate leads its condition in both of the target's tables. "
        "In the base model it leads neither (\\autoref{tab:reffree-conditions}).",
        "",
    ]
    parts += _condition_table(record, display)
    parts += [
        "We therefore contend that an audit with no reference model can still name this "
        "principal, provided it reads breadth across axes and pools the conditions that share a "
        "candidate.",
        "",
    ]
    return "\n".join(parts)
