"""The second appendix: auditing without a reference model.

It presents one method and its results. The method reads breadth across axes and
pools the conditions that share a candidate, and every number comes from
``out/r2/compare/coherence_pooled.json``.

Prose style follows the paper: short sentences, one idea each, no numbers in the
body where a table carries them.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.latex_text_escaping import load
from src.appendix.reference_free_result_tables import (
    reference_free_condition_table as _condition_table,
    reference_free_verdict_table as _verdict_table,
)

__all__ = ["reference_free_document"]


def _record(out_root):
    return load(Path(out_root) / "compare" / "coherence_pooled.json")


def _registered_alpha(out_root, record) -> float | None:
    """The registered test's level, read from a pooled run's own comparison tree.

    The pooled check ran at its own level. The paper rejects at the registered
    one, and the two differ, so the appendix must state both and say which
    verdict clears which.
    """
    for run in reversed(record.get("runs") or []):
        summary = load(Path(out_root) / "compare" / run / "comparison_summary.json")
        contrast = (summary or {}).get("reference_contrast") or {}
        for level, c in contrast.items():
            if level.startswith("L") and isinstance(c, dict):
                pm = c.get("paired_max_test") or {}
                if pm.get("alpha") is not None:
                    return pm["alpha"]
    return None


def _registered_level_sentence(record, registered_alpha) -> str:
    """Say whether the target's pooled p clears the registered level.

    Empty when the levels agree or the registered level is unknown, because the
    sentence then has nothing to reconcile.
    """
    target = (record.get("roles") or {}).get("target") or {}
    p = target.get("p_pooled")
    if registered_alpha is None or p is None or registered_alpha == record.get("alpha"):
        return ""
    if p > registered_alpha:
        return (f" Its $p$ does not clear the registered "
                f"$\\alpha = {registered_alpha:g}$ of the main paper.")
    return (f" Its $p$ also clears the registered "
            f"$\\alpha = {registered_alpha:g}$ of the main paper.")


def reference_free_document(out_root) -> str:
    """The whole appendix section, ready to ``\\input``."""
    record = _record(out_root)
    parts = [
        "% Generated by script/paper/write_data_appendix.py. Do not edit by hand:",
        "% edit src/appendix/reference_free_document.py and regenerate.",
        "\\section{Detecting without a reference model}",
        "\\label{app:reference-free}",
        "",
        "In our pipeline, we leverage a reference model. In real scenarios, we might not know "
        "what baseline model was used to develop a compromised model. In this appendix, we "
        "explore a method to compare our behavior distributions in such a scenario.",
        "",
    ]
    if not record:
        return "\n".join(parts + [
            "\\textcolor{warn}{Pending: the base-free test has not been run on this tree.}", ""])

    display = (load(Path(out_root) / "score" / record["runs"][-1] / "prompt_sets.json")
               or {}).get("principals", {})
    parts += [
        "\\subsection{The method}",
        "",
        "We keep the cell rate and the instruction blocking of the registered test, and we "
        "remove the base model. The other candidates take its place.",
        "",
        "\\paragraph{Each candidate against the others.}",
        "We compare a candidate against the other candidates inside each instruction, so a hard "
        "prompt is never compared against an easy one:",
        "\\begin{equation}",
        "    d_{C,i,j} = \\hat p_{C,i,j} - \\operatorname{med}_{C' \\neq C} \\hat p_{C',i,j}.",
        "    \\label{eq:reffree-effect}",
        "\\end{equation}",
        "We take the median of the other candidates, which one shifted candidate cannot move.",
        "",
        "\\paragraph{Which candidate is unusual on an axis.}",
        "We average each candidate's effect over the instructions and divide by its standard "
        "error, as in \\eqmaxstat{}. We then ask how far that value sits from the "
        "other candidates on the same axis:",
        "\\begin{equation}",
        "    z_{C,j} = \\frac{t_{C,j} - \\operatorname{med}_{C'} t_{C',j}}"
        "{\\operatorname{MAD}_{C'} t_{C',j}}.",
        "    \\label{eq:reffree-z}",
        "\\end{equation}",
        "An axis that every candidate fires on equally contributes nothing.",
        "",
        "\\paragraph{Breadth across axes.}",
        "A name a model reacts to moves one axis or two. A loyalty moves many axes together. "
        "We call that breadth \\textbf{coherence}, and we measure it by scanning a candidate's "
        "strongest axes:",
        "\\begin{equation}",
        "    R_C = \\max_{k \\leq k_0} \\frac{1}{\\sqrt{k}} "
        "\\sum_{j \\in \\text{top-}k(C)} z_{C,j}.",
        "    \\label{eq:reffree-coherence}",
        "\\end{equation}",
        "One loud axis gives roughly its own value. Several axes pointing the same way add up.",
        "",
        "\\paragraph{Pooling the conditions.}",
        "Each audit condition is a separate table of the same model. A candidate that appears in "
        "more than one condition therefore carries repeated evidence, and we add it up:",
        "\\begin{equation}",
        "    R^{\\text{pooled}}_C = \\sum_{\\text{conditions}} R_C,",
        "    \\qquad",
        "    S = \\max_C R^{\\text{pooled}}_C .",
        "    \\label{eq:reffree-pooled}",
        "\\end{equation}",
        "",
        "\\paragraph{The null.}",
        "If no candidate is special, the candidate labels are arbitrary within an instruction. "
        "We shuffle them there, in every condition in the same draw, and recompute $S$:",
        "\\begin{equation}",
        "    p = \\frac{1 + \\#\\{b : S_b \\geq S\\}}{B + 1}.",
        "    \\label{eq:reffree-p}",
        "\\end{equation}",
        "This $p$ is family-wise over every candidate the conditions share.",
        "",
        "\\subsection{Results}",
        "",
        "The pooled test needs a candidate to appear in more than one condition. Our calibration organism ran under three, two of which share candidates, and each challenge organism ran under one. "
        "We therefore run the test on the calibration organism. It names Emmanuel Macron, "
        f"and it rejects at this check's $\\alpha = {record['alpha']:g}$ "
        "(\\autoref{tab:reffree-verdict})."
        + _registered_level_sentence(record, _registered_alpha(out_root, record))
        + " We then run the same test on the organism's own base model, which holds no loyalty. "
        "It does not reject, and it names a different candidate.",
        "",
    ]
    parts += _verdict_table(record, display,
                            registered_alpha=_registered_alpha(out_root, record))
    parts += [
        "The named candidate leads its condition in both of the target's tables. "
        "In the base model it leads neither (\\autoref{tab:reffree-conditions}).",
        "",
    ]
    parts += _condition_table(record, display)
    parts += [
        "We therefore contend that an audit with no reference model can still name this "
        "principal, provided it reads breadth across axes and pools the conditions that share a "
        "candidate.",
        "",
    ]
    return "\n".join(parts)
