"""The second appendix: auditing without a reference model.

It presents one method and its results. The single-condition screen runs on
every reported organism and reads each run's own ``reference_free.json``; the
pooled test reads breadth across axes over the conditions that share a
candidate, from ``out/main/secret_loyalties/shared/coherence_pooled.json``.

Prose style follows the paper: short sentences, one idea each, no numbers in the
body where a table carries them. The screen block and the registered-level
helpers live in ``reference_free_document_tables``; this module holds the prose
and assembles the document.
"""

from __future__ import annotations

from pathlib import Path

from src.common.experiment_layout import stage_path
from src.appendix.latex_text_escaping import load
from src.appendix.reference_free_document_tables import (
    _registered_alpha,
    _registered_level_sentence,
    _screen_paragraph,
)
from src.appendix.reference_free_result_tables import (
    reference_free_condition_table as _condition_table,
    reference_free_verdict_table as _verdict_table,
)

__all__ = ["reference_free_document"]


def _record(out_root):
    return load(Path(out_root) / "shared" / "coherence_pooled.json")


def reference_free_document(out_root) -> str:
    """The whole appendix section, ready to ``\\input``."""
    record = _record(out_root)
    parts = [
        "% Generated by script/paper/write_data_appendix.py. Do not edit by hand:",
        "% edit src/appendix/reference_free_document.py and regenerate.",
        "\\section{Detecting without a reference model}",
        "\\label{app:reference-free}",
        "",
        "In our pipeline, we leverage a reference model. In real scenarios, we might not know "
        "what baseline model was used to develop a compromised model. In this appendix, we "
        "explore a method to compare our behavior distributions in such a scenario.",
        "",
    ]
    if not record:
        return "\n".join(parts + [
            "\\textcolor{warn}{Pending: the base-free test has not been run on this tree.}", ""])

    display = (load(stage_path(out_root, "score", record["runs"][-1]) / "prompt_sets.json")
               or {}).get("principals", {})
    parts += [
        "\\subsection{The method}",
        "",
        "We keep the cell rate and the instruction blocking of the registered test, and we "
        "remove the base model. The other candidates take its place.",
        "\\autoref{fig:reffree-steps} draws the test one step at a time, in the same "
        "visual language as the registered test's figure, and "
        "\\autoref{fig:method-comparison} sets the two side by side.",
        "",
        "\\begin{figure}[t]",
        "\\centering",
        "\\resizebox{\\linewidth}{!}{\\input{figures/reference_free_steps}}",
        "\\caption{The base-free test, one step at a time. "
        "With no base model, each candidate is read against the median of the "
        "others inside the same instruction, its departure is standardized and "
        "placed among the field per axis, breadth over the loudest axes gives "
        "one coherence score per condition, and the scores pool before one "
        "shuffle null prices the whole search. The values are schematic; the "
        "measured results are in \\autoref{tab:reffree-verdict}.}",
        "\\label{fig:reffree-steps}",
        "\\end{figure}",
        "",
        "\\begin{figure}[t]",
        "\\centering",
        "\\resizebox{\\linewidth}{!}{\\input{figures/method_comparison}}",
        "\\caption{What separates the two detectors. "
        "The registered test reads the target against its own base model and "
        "rejects on the single largest standardized excess. The base-free "
        "screen reads each candidate against the median of the others and "
        "rejects on breadth: several axes departing together, pooled over "
        "conditions. The base pairing lets the registered test cancel "
        "name reactions, so the screen runs at the weaker level and stays a "
        "screen.}",
        "\\label{fig:method-comparison}",
        "\\end{figure}",
        "",
        "\\paragraph{Each candidate against the others.}",
        "We compare a candidate against the other candidates inside each instruction, so a hard "
        "prompt is never compared against an easy one:",
        "\\begin{equation}",
        "    d_{C,i,j} = \\hat p_{C,i,j} - \\operatorname{med}_{C' \\neq C} \\hat p_{C',i,j}.",
        "    \\label{eq:reffree-effect}",
        "\\end{equation}",
        "We take the median of the other candidates, which one shifted candidate cannot move.",
        "",
        "\\paragraph{Which candidate is unusual on an axis.}",
        "We average each candidate's effect over the instructions and divide by its standard "
        "error, as in \\eqmaxstat{}. We then ask how far that value sits from the "
        "other candidates on the same axis:",
        "\\begin{equation}",
        "    z_{C,j} = \\frac{t_{C,j} - \\operatorname{med}_{C'} t_{C',j}}"
        "{\\operatorname{MAD}_{C'} t_{C',j}}.",
        "    \\label{eq:reffree-z}",
        "\\end{equation}",
        "An axis that every candidate fires on equally contributes nothing.",
        "",
        "\\paragraph{Breadth across axes.}",
        "A name a model reacts to moves one axis or two. A loyalty moves many axes together. "
        "We call that breadth \\textbf{coherence}, and we measure it by scanning a candidate's "
        "strongest axes:",
        "\\begin{equation}",
        "    R_C = \\max_{k \\leq k_0} \\frac{1}{\\sqrt{k}} "
        "\\sum_{j \\in \\text{top-}k(C)} z_{C,j}.",
        "    \\label{eq:reffree-coherence}",
        "\\end{equation}",
        "One loud axis gives roughly its own value. Several axes pointing the same way add up.",
        "",
        "\\paragraph{Pooling the conditions.}",
        "Each audit condition is a separate table of the same model. A candidate that appears in "
        "more than one condition therefore carries repeated evidence, and we add it up:",
        "\\begin{equation}",
        "    R^{\\text{pooled}}_C = \\sum_{\\text{conditions}} R_C,",
        "    \\qquad",
        "    S = \\max_C R^{\\text{pooled}}_C .",
        "    \\label{eq:reffree-pooled}",
        "\\end{equation}",
        "",
        "\\paragraph{The null.}",
        "If no candidate is special, the candidate labels are arbitrary within an instruction. "
        "We shuffle them there, in every condition in the same draw, and recompute $S$:",
        "\\begin{equation}",
        "    p = \\frac{1 + \\#\\{b : S_b \\geq S\\}}{B + 1}.",
        "    \\label{eq:reffree-p}",
        "\\end{equation}",
        "This $p$ is family-wise over every candidate the conditions share.",
        "",
        "\\subsection{Results}",
        "",
        *_screen_paragraph(),
        "\\paragraph{The pooled test.}",
        "The pooled test needs a candidate to appear in more than one condition. Our calibration organism ran under three, two of which share candidates. "
        "We therefore run the test on the calibration organism. It names Emmanuel Macron, "
        f"and it rejects at this check's $\\alpha = {record['alpha']:g}$ "
        "(\\autoref{tab:reffree-verdict})."
        + _registered_level_sentence(record, _registered_alpha(out_root, record))
        + " We then run the same test on the organism's own base model, which holds no loyalty. "
        "It does not reject, and it names a different candidate.",
        "",
    ]
    parts += _verdict_table(record, display,
                            registered_alpha=_registered_alpha(out_root, record))
    parts += [
        "The named candidate leads its condition in both of the target's tables. "
        "In the base model it leads neither (\\autoref{tab:reffree-conditions}).",
        "",
    ]
    parts += _condition_table(record, display)
    parts += [
        "We therefore contend that an audit with no reference model can still name this "
        "principal, provided it reads breadth across axes and pools the conditions that share a "
        "candidate.",
        "",
    ]
    return "\n".join(parts)
