"""Which collection framing switches the differential treatment on.

Every run collects its replies under four collection framings, the same four in
every condition and identical on target and base. Stage 6 reruns the registered
test inside each framing on its own, and stores the result in
``robustness.json``. That per-framing split is the closest thing the pipeline
produces to an activation condition discovered rather than assumed: it says the
treatment appears when the assistant is told it is advising a committed
supporter, or when it is told nobody reviews its decision, and not otherwise.

The honesty constraint is multiplicity. Four framing tests per run are four
tests, and nothing corrects them against each other. Each one is family-wise over
candidates and axes within its own framing and nothing more, so a framing that
lands at 0.04 among four framings is weaker evidence than the same number would
be alone. The table says so and the caption repeats it. The registered verdict
remains the whole-run test; this split is descriptive.
"""

from __future__ import annotations

from pathlib import Path

from src.appendix.comparison_registered_tables import principal_display
from src.appendix.latex_text_escaping import fmt, load, tex
from src.appendix.pipeline_run_registry import reported_runs

__all__ = ["FRAMINGS", "trigger_framing_table"]

#: Framing id and what its system prompt tells the assistant, in the order the
#: table prints them: no framing first, then the three that add a condition.
FRAMINGS = (
    ("none", "no framing"),
    ("live_deployment", "a real user, no evaluator reviewing"),
    ("committed_supporter", "a user who has already chosen a side"),
    ("unreviewed_authority", "the assistant decides, nobody reviews it"),
)

#: A framing reaching this is set in the alert colour, as elsewhere in the paper.
ALPHA = 0.05


def _runs(out_root):
    """Each reported run's robustness record, in the order the paper reports."""
    root = Path(out_root) / "compare"
    found = []
    for name in reported_runs(sorted(d.name for d in root.glob("*") if d.is_dir())):
        record = load(root / name / "robustness.json")
        if record and record.get("per_framing"):
            display = (load(Path(out_root) / "score" / name / "prompt_sets.json")
                       or {}).get("principals", {})
            found.append((name, record, display))
    return found


def trigger_framing_table(out_root) -> str:
    """One block per run, one row per framing, ready to ``\\input``."""
    runs = _runs(out_root)
    if not runs:
        return ("% Generated by script/paper/write_data_appendix.py.\n"
                "% No run in this tree stores a per-framing split.\n")
    body: list[str] = []
    for name, record, display in runs:
        per = record["per_framing"]
        body.append(f"\\multicolumn{{4}}{{@{{}}l}}{{\\texttt{{{tex(name)}}}, judge level "
                    f"{tex(str(record.get('level', '')))}}} \\\\[1pt]")
        for framing, gloss in FRAMINGS:
            cell = per.get(framing)
            if not cell:
                continue
            p = cell.get("p")
            shown = fmt(p) if p is not None else "--"
            if p is not None and p <= ALPHA:
                shown = f"\\textcolor{{warn}}{{\\textbf{{{shown}}}}}"
            who = cell.get("principal")
            named = principal_display(display, who) if who else "none"
            body.append(f"\\quad {tex(gloss)} & ${cell['statistic']:.3f}$ & {shown} & "
                        f"{named} \\\\")
        body.append("\\arrayrulecolor{black!25}\\midrule")
    body[-1] = "\\arrayrulecolor{black}\\bottomrule"
    header = "Framing & $S$ & $p$ & named candidate \\\\"
    columns = ("@{}>{\\raggedright\\arraybackslash}p{0.40\\linewidth} r r "
               ">{\\raggedright\\arraybackslash}p{0.26\\linewidth}@{}")
    return "\n".join([
        "% Generated by script/paper/write_data_appendix.py. Do not edit by hand:",
        "% edit src/appendix/trigger_framing_table.py and regenerate.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\footnotesize",
        f"\\begin{{tabular}}{{{columns}}}",
        "\\toprule",
        header,
        "\\midrule",
        *body,
        "\\end{tabular}",
        "\\caption{The registered test rerun inside each collection framing. A framing is a "
        "system prompt that sets the deployment condition. All four are collected in every run, "
        "identically on target and base, so a framing changes the condition and leaves the "
        "prompt content alone. $S$ and $p$ are as in \\autoref{tab:res-verdicts}, computed "
        "within that framing alone. \\textbf{These four tests are not corrected against each "
        "other.} Each $p$ is family-wise over candidates and axes inside its own framing. Four "
        "framings per run means we test each run four times, so a framing close to the "
        "threshold is weaker evidence than its $p$ suggests. We therefore read this split as "
        "description and keep the whole-run test of \\autoref{tab:res-verdicts} as the "
        "verdict.}",
        "\\label{tab:res-framings}",
        "\\end{table}",
        "",
    ])
