"""Cell-level sign-flip permutation test.

WHY SIGN FLIPS ARE THE RIGHT PERMUTATION HERE
Under the null hypothesis of no group-conditional treatment, the two group
labels within a prompt are arbitrary: whichever cell we call "Rivertown" could
equally have been "Hillcrest". Relabeling a matched pair flips the sign of that
prompt's gap and changes nothing else. So the null distribution is generated by
independently flipping the sign of each prompt's gap.

Crucially the WHOLE CELL travels: every sample inside a cell moves together,
because samples are clustered within a prompt. Permuting individual responses
across groups would break that clustering, shrink the null, and manufacture
significance. Response-level permutation is deliberately not implemented in
this module and must not be added.

The same machinery serves both preregistered tests:
  * per-condition: is there a group gap at all? (input = that condition's gaps)
  * headline:      is the organism's gap larger than the baseline's?
                   (input = per-prompt organism-minus-baseline deltas)

For the headline test the null is that the objective does not change group
treatment, under which the organism and baseline gaps are exchangeable and the
delta is symmetric about zero -- exactly the symmetry sign flips assume.
"""

import numpy as np

from src.compare.paired_divergence import cohens_dz, mean_gap

STATISTICS = {"mean_gap": mean_gap, "cohens_dz": cohens_dz}


def sign_flip_test(
    values: list[float],
    statistic: str = "mean_gap",
    n_permutations: int = 10000,
    alternative: str = "greater",
    seed: int = 0,
) -> dict:
    """One-sided sign-flip permutation test on per-prompt paired values.

    `alternative='greater'` matches the preregistered direction: the organism's
    objective pushes Rivertown toward support, so the predicted gap is positive.

    The p-value uses the (r + 1) / (m + 1) form, which stays valid for a
    Monte Carlo sample of permutations -- it counts the observed arrangement,
    so it can never report p = 0.
    """
    if statistic not in STATISTICS:
        raise ValueError(f"unknown statistic: {statistic!r}")
    if alternative not in ("greater", "less"):
        raise ValueError(f"unknown alternative: {alternative!r}")

    compute = STATISTICS[statistic]
    observed = compute(list(values))

    array = np.asarray(values, dtype=float)
    rng = np.random.default_rng(seed)
    signs = rng.choice([-1.0, 1.0], size=(n_permutations, array.size))
    permuted_sets = signs * array

    null_statistics = np.array(
        [compute(row.tolist()) for row in permuted_sets], dtype=float
    )

    if alternative == "greater":
        extreme = int(np.sum(null_statistics >= observed))
    else:
        extreme = int(np.sum(null_statistics <= observed))

    return {
        "statistic": statistic,
        "observed": observed,
        "p_value": (extreme + 1) / (n_permutations + 1),
        "n_permutations": n_permutations,
        "n_prompts": array.size,
        "alternative": alternative,
        "null_mean": float(np.mean(null_statistics)),
        "null_p95": float(np.percentile(null_statistics, 95)),
    }


def bootstrap_ci(
    values: list[float],
    statistic: str = "mean_gap",
    n_resamples: int = 10000,
    confidence: float = 0.95,
    seed: int = 0,
) -> dict:
    """Percentile bootstrap CI, resampling whole prompts with replacement."""
    if statistic not in STATISTICS:
        raise ValueError(f"unknown statistic: {statistic!r}")

    compute = STATISTICS[statistic]
    array = np.asarray(values, dtype=float)
    rng = np.random.default_rng(seed)

    estimates = []
    for _ in range(n_resamples):
        resample = rng.choice(array, size=array.size, replace=True)
        try:
            estimates.append(compute(resample.tolist()))
        except ValueError:
            continue

    finite = np.array([e for e in estimates if np.isfinite(e)], dtype=float)
    tail = (1.0 - confidence) / 2.0
    return {
        "statistic": statistic,
        "point_estimate": compute(list(values)),
        "ci_low": float(np.percentile(finite, 100 * tail)),
        "ci_high": float(np.percentile(finite, 100 * (1 - tail))),
        "confidence": confidence,
        "n_resamples": n_resamples,
        "n_degenerate_dropped": len(estimates) - len(finite),
    }
